
require('dotenv').config();
const express = require('express');
const nodemailer = require('nodemailer');
const helmet = require('helmet');
const cors = require('cors');
const morgan = require('morgan');
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const app = express();
const PORT = process.env.PORT || 8080;
const DATA_PATH = path.join(__dirname, 'data', 'db.json');

app.use(helmet({ contentSecurityPolicy: false }));
app.use(cors());
app.use(express.json({ limit: '2mb' }));
app.use(morgan('dev'));
app.use(express.static(path.join(__dirname, 'public')));

function readDb(){ try { return JSON.parse(fs.readFileSync(DATA_PATH, 'utf8')); } catch(e){ return {users:[],patients:[],notes:[],orders:[],labs:[],imaging:[],alerts:[],services:[],audit:[]}; } }
function writeDb(db){ fs.writeFileSync(DATA_PATH, JSON.stringify(db, null, 2), 'utf8'); }
function normalize(s){ return String(s||'').trim(); }
function now(){ return new Date().toISOString(); }
function hashPassword(password, salt = crypto.randomBytes(16).toString('hex')){ const hash = crypto.pbkdf2Sync(password, salt, 100000, 32, 'sha256').toString('hex'); return `${salt}:${hash}`; }
function verifyPassword(password, stored){ if(!stored || !stored.includes(':')) return false; const [salt, hash] = stored.split(':'); const candidate = crypto.pbkdf2Sync(password, salt, 100000, 32, 'sha256').toString('hex'); try{return crypto.timingSafeEqual(Buffer.from(hash,'hex'), Buffer.from(candidate,'hex'));}catch(e){return false;} }
function token(){ return crypto.randomBytes(24).toString('hex'); }
function otp(){ return String(Math.floor(100000 + Math.random()*900000)); }
function publicUser(u){ return { id:u.id, username:u.username, fullName:u.fullName, email:u.email, department:u.department, verified:!!u.verified, role:u.role||'doctor' }; }
function audit(user, action, target, detail){ const db=readDb(); db.audit=db.audit||[]; db.audit.unshift({ts:now(), user:user?user.username:'system', action, target, detail}); db.audit=db.audit.slice(0,500); writeDb(db); }
function requireAuth(req,res,next){ const header=req.headers.authorization||''; const t=header.startsWith('Bearer ')?header.slice(7):''; const db=readDb(); const user=db.users.find(u=>u.sessionToken===t && u.sessionExp && u.sessionExp>Date.now()); if(!user) return res.status(401).json({ok:false,error:'Unauthorized'}); req.user=user; next(); }
async function sendVerificationEmail(user, code){
  if(String(process.env.EMAIL_DEV_MODE||'true').toLowerCase()==='true'){ console.log(`[DEV EMAIL] OTP for ${user.email}: ${code}`); return {dev:true}; }
  const transporter=nodemailer.createTransport({host:process.env.SMTP_HOST,port:Number(process.env.SMTP_PORT||587),secure:String(process.env.SMTP_SECURE||'false').toLowerCase()==='true',auth:{user:process.env.SMTP_USER,pass:process.env.SMTP_PASS}});
  await transporter.sendMail({from:process.env.MAIL_FROM||process.env.SMTP_USER,to:user.email,subject:'Your HGY CareBoard verification code',text:`Hello ${user.fullName},\n\nYour HGY CareBoard verification code is: ${code}\n\nThis code expires in 10 minutes.\n\nYAOUNDE GENERAL HOSPITAL`,html:`<h2>HGY CareBoard</h2><p>Your code is:</p><div style="font-size:30px;font-weight:bold;letter-spacing:4px">${code}</div><p>YAOUNDE GENERAL HOSPITAL</p>`});
  return {dev:false};
}
function ensureDemoUser(){ const db=readDb(); if(!db.users.find(u=>u.username==='dr.alvarez')){ db.users.push({id:'u-demo-1',username:'dr.alvarez',fullName:'Dr. Sofia Alvarez',email:'demo@hgy.local',department:'ICU',role:'doctor',verified:true,passwordHash:hashPassword('Password!123'),createdAt:now()}); writeDb(db); } }
ensureDemoUser();

function generateVitals(patientId){ const base=Math.abs([...String(patientId)].reduce((a,c)=>a+c.charCodeAt(0),0))%20; const nowMs=Date.now(); const make=(n,min,amp,speed,decimals=0)=>Array.from({length:n},(_,i)=>({t:nowMs-(n-i)*1000,v:Math.round((min+amp+Math.sin((nowMs/1000+i)/speed)*amp+Math.random()*3)*(decimals?10:1))/(decimals?10:1)})); return {HR:make(100,70+base,9,4),SPO2:make(100,95,2,5),RR:make(100,14,3,6),TEMP:make(100,36.6,.35,7,1),BP_SYS:make(100,110+base,12,8),BP_DIA:make(100,70,6,9),PEEP:make(100,5,2,12),VT:make(100,400,50,10),ETCO2:make(100,34,4,8)}; }
function calculateRisk(patient, vitals){ const latest={}; for(const [k,arr] of Object.entries(vitals)){ latest[k]=arr[arr.length-1].v; } let score=0; if(latest.HR>110||latest.HR<50)score+=2; if(latest.SPO2<92)score+=3; if(latest.RR>24||latest.RR<8)score+=2; if(latest.TEMP>38.5||latest.TEMP<35)score+=1; if(latest.BP_SYS<90||latest.BP_SYS>160)score+=2; if(patient.status==='critical')score+=3; if(patient.tag==='High Risk')score+=2; const level=score>=7?'high':score>=4?'medium':'low'; return {score,level,latest}; }
function localAiAnalysis(patient,vitals){ const risk=calculateRisk(patient,vitals); const latest=risk.latest; const recommendations=[]; if(latest.SPO2<94)recommendations.push('Review oxygenation, probe position, oxygen delivery, and ventilator settings if applicable.'); if(latest.HR>105)recommendations.push('Review pain, fever, anxiety, hypovolemia, or rhythm issues.'); if(latest.BP_SYS<100)recommendations.push('Review perfusion, fluid balance, and vasopressor needs according to clinician judgment.'); if(patient.tag==='Isolation')recommendations.push('Maintain PPE and isolation workflow.'); if(recommendations.length===0)recommendations.push('Continue routine monitoring and reassess trends.'); return {mode:'mock',generatedAt:now(),patient:{name:patient.name,mrn:patient.mrn,unit:patient.unit,bed:patient.bed},risk,summary:`${patient.name} is currently classified as ${risk.level.toUpperCase()} risk based on simulated vitals, status, and tags.`,recommendations,disclaimer:'Demo clinical decision-support style summary only. Not medical advice.'}; }
async function externalAiAnalysis(patient,vitals){ const key=process.env.OPENAI_API_KEY; if(!key)return localAiAnalysis(patient,vitals); const prompt=`Summarize patient for doctor without diagnosis. Patient: ${JSON.stringify(patient)} Risk: ${JSON.stringify(calculateRisk(patient,vitals))}. Return concise clinical dashboard recommendations.`; const response=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${key}`},body:JSON.stringify({model:process.env.OPENAI_MODEL||'gpt-4.1-mini',input:prompt})}); if(!response.ok)return localAiAnalysis(patient,vitals); const data=await response.json(); return {mode:'ai',generatedAt:now(),raw:data,fallback:localAiAnalysis(patient,vitals)}; }

app.post('/api/signup', async (req,res)=>{ const b=req.body||{}; const fullName=normalize(b.fullName), username=normalize(b.username).toLowerCase(), email=normalize(b.email).toLowerCase(), department=normalize(b.department)||'ICU', password=String(b.password||''); if(!fullName||!username||!email||!password)return res.status(400).json({ok:false,error:'Missing required fields'}); if(password.length<8||!/\d/.test(password))return res.status(400).json({ok:false,error:'Password must be at least 8 characters and include a number'}); if(!/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(email))return res.status(400).json({ok:false,error:'Invalid email'}); const db=readDb(); if(db.users.find(u=>u.username===username))return res.status(409).json({ok:false,error:'Username already exists'}); if(db.users.find(u=>u.email===email))return res.status(409).json({ok:false,error:'Email already exists'}); const code=otp(); const user={id:'u-'+Date.now(),username,fullName,email,department,role:'doctor',verified:false,passwordHash:hashPassword(password),otpHash:hashPassword(code),otpExp:Date.now()+10*60*1000,createdAt:now()}; db.users.push(user); writeDb(db); try{const sent=await sendVerificationEmail(user,code); res.json({ok:true,username,message:'Verification code sent to email',devOtp:sent.dev?code:undefined});}catch(e){res.status(500).json({ok:false,error:'Could not send verification email. Check SMTP settings.'});} });
app.post('/api/resend-code', async (req,res)=>{ const username=normalize(req.body.username).toLowerCase(); const db=readDb(); const user=db.users.find(u=>u.username===username); if(!user)return res.status(404).json({ok:false,error:'User not found'}); if(user.verified)return res.json({ok:true,message:'Already verified'}); const code=otp(); user.otpHash=hashPassword(code); user.otpExp=Date.now()+10*60*1000; writeDb(db); const sent=await sendVerificationEmail(user,code); res.json({ok:true,devOtp:sent.dev?code:undefined}); });
app.post('/api/verify',(req,res)=>{ const username=normalize(req.body.username).toLowerCase(), code=normalize(req.body.code); const db=readDb(); const user=db.users.find(u=>u.username===username); if(!user)return res.status(404).json({ok:false,error:'User not found'}); if(user.verified)return res.json({ok:true,message:'Already verified'}); if(!user.otpHash||!user.otpExp||user.otpExp<Date.now())return res.status(400).json({ok:false,error:'Code expired'}); if(!verifyPassword(code,user.otpHash))return res.status(400).json({ok:false,error:'Invalid code'}); user.verified=true; delete user.otpHash; delete user.otpExp; writeDb(db); res.json({ok:true}); });
app.post('/api/login',(req,res)=>{ const username=normalize(req.body.username).toLowerCase(), password=String(req.body.password||''); const db=readDb(); const user=db.users.find(u=>u.username===username); if(!user||!verifyPassword(password,user.passwordHash))return res.status(401).json({ok:false,error:'Invalid credentials'}); if(!user.verified)return res.status(403).json({ok:false,error:'Account not verified',needsVerification:true}); user.sessionToken=token(); user.sessionExp=Date.now()+8*60*60*1000; writeDb(db); audit(user,'login','user',user.username); res.json({ok:true,token:user.sessionToken,user:publicUser(user)}); });
app.post('/api/logout',requireAuth,(req,res)=>{ const db=readDb(); const user=db.users.find(u=>u.id===req.user.id); if(user){delete user.sessionToken;delete user.sessionExp;writeDb(db);} res.json({ok:true}); });
app.get('/api/me',requireAuth,(req,res)=>res.json({ok:true,user:publicUser(req.user)}));
app.get('/api/departments',requireAuth,(req,res)=>res.json({ok:true,departments:['ICU','Emergency','Radiology','Surgery','Pediatrics','Maternity','Internal Med','Laboratory','Pharmacy','Administration','Biomedical','Ambulance']}));
app.get('/api/services',requireAuth,(req,res)=>res.json({ok:true,services:readDb().services||[]}));
app.get('/api/patients',requireAuth,(req,res)=>{ const {unit,q,status}=req.query; let patients=readDb().patients||[]; if(unit)patients=patients.filter(p=>p.unit===unit); if(status)patients=patients.filter(p=>p.status===status); if(q){const s=String(q).toLowerCase(); patients=patients.filter(p=>[p.name,p.mrn,p.bed,p.unit,p.tag,p.diagnosis].some(v=>String(v||'').toLowerCase().includes(s)));} res.json({ok:true,patients}); });
app.post('/api/patients',requireAuth,(req,res)=>{ const p=req.body||{}; if(!p.name||!p.mrn||!p.unit||!p.bed)return res.status(400).json({ok:false,error:'Missing patient fields'}); const db=readDb(); const patient={id:'p-'+Date.now(),mrn:normalize(p.mrn),name:normalize(p.name),unit:normalize(p.unit),bed:normalize(p.bed),room:normalize(p.room)||normalize(p.bed),age:normalize(p.age),sex:normalize(p.sex),tag:normalize(p.tag),notes:normalize(p.notes),diagnosis:normalize(p.diagnosis),allergies:normalize(p.allergies),bloodType:normalize(p.bloodType),attending:normalize(p.attending),primaryNurse:normalize(p.primaryNurse),status:normalize(p.status)||'stable',admittedAt:normalize(p.admittedAt)||now(),deviceMap:p.deviceMap||{}}; db.patients.unshift(patient); writeDb(db); audit(req.user,'create','patient',patient.mrn); res.json({ok:true,patient}); });
app.put('/api/patients/:id',requireAuth,(req,res)=>{ const db=readDb(); const i=db.patients.findIndex(p=>p.id===req.params.id); if(i<0)return res.status(404).json({ok:false,error:'Patient not found'}); db.patients[i]={...db.patients[i],...req.body,id:req.params.id}; writeDb(db); audit(req.user,'update','patient',db.patients[i].mrn); res.json({ok:true,patient:db.patients[i]}); });
app.delete('/api/patients/:id',requireAuth,(req,res)=>{ const db=readDb(); const old=db.patients.find(p=>p.id===req.params.id); db.patients=db.patients.filter(p=>p.id!==req.params.id); writeDb(db); audit(req.user,'delete','patient',old?old.mrn:req.params.id); res.json({ok:true}); });
app.get('/api/patients/:id/detail',requireAuth,(req,res)=>{ const db=readDb(); const patient=(db.patients||[]).find(p=>p.id===req.params.id); if(!patient)return res.status(404).json({ok:false,error:'Patient not found'}); const related=key=>(db[key]||[]).filter(x=>x.patientId===patient.id); res.json({ok:true,detail:{patient,notes:related('notes'),orders:related('orders'),labs:related('labs'),imaging:related('imaging'),alerts:related('alerts')}}); });
app.post('/api/patients/:id/notes',requireAuth,(req,res)=>{ const db=readDb(); const patient=(db.patients||[]).find(p=>p.id===req.params.id); if(!patient)return res.status(404).json({ok:false,error:'Patient not found'}); db.notes=db.notes||[]; const item={id:'n-'+Date.now(),patientId:patient.id,ts:now(),author:req.user.fullName||req.user.username,text:normalize(req.body.text)}; db.notes.unshift(item); writeDb(db); audit(req.user,'create','note',patient.mrn); res.json({ok:true,note:item}); });
app.post('/api/patients/:id/orders',requireAuth,(req,res)=>{ const db=readDb(); const patient=(db.patients||[]).find(p=>p.id===req.params.id); if(!patient)return res.status(404).json({ok:false,error:'Patient not found'}); db.orders=db.orders||[]; const item={id:'o-'+Date.now(),patientId:patient.id,ts:now(),author:req.user.fullName||req.user.username,status:'Active',text:normalize(req.body.text)}; db.orders.unshift(item); writeDb(db); audit(req.user,'create','order',patient.mrn); res.json({ok:true,order:item}); });
app.post('/api/patients/:id/alerts',requireAuth,(req,res)=>{ const db=readDb(); const patient=(db.patients||[]).find(p=>p.id===req.params.id); if(!patient)return res.status(404).json({ok:false,error:'Patient not found'}); db.alerts=db.alerts||[]; const item={id:'a-'+Date.now(),patientId:patient.id,ts:now(),severity:normalize(req.body.severity)||'Medium',text:normalize(req.body.text)}; db.alerts.unshift(item); writeDb(db); audit(req.user,'create','alert',patient.mrn); res.json({ok:true,alert:item}); });
app.get('/api/vitals/:id',requireAuth,(req,res)=>{ const db=readDb(); const patient=db.patients.find(p=>p.id===req.params.id)||db.patients[0]; const vitals=generateVitals(req.params.id); res.json({ok:true,patient,vitals,risk:calculateRisk(patient,vitals)}); });
app.get('/api/central',requireAuth,(req,res)=>{ const db=readDb(); const unit=req.query.unit; let patients=db.patients||[]; if(unit)patients=patients.filter(p=>p.unit===unit); const cards=patients.map(p=>({patient:p,risk:calculateRisk(p,generateVitals(p.id))})); res.json({ok:true,cards}); });
app.get('/api/ai/analyze/:id',requireAuth,async(req,res)=>{ const db=readDb(); const patient=db.patients.find(p=>p.id===req.params.id); if(!patient)return res.status(404).json({ok:false,error:'Patient not found'}); const vitals=generateVitals(patient.id); const result=process.env.AI_MODE==='openai'?await externalAiAnalysis(patient,vitals):localAiAnalysis(patient,vitals); audit(req.user,'ai_analyze','patient',patient.mrn); res.json({ok:true,analysis:result}); });
app.get('/api/ai/hospital',requireAuth,(req,res)=>{ const db=readDb(); const ranked=(db.patients||[]).map(p=>({patient:p,risk:calculateRisk(p,generateVitals(p.id))})).sort((a,b)=>b.risk.score-a.risk.score); res.json({ok:true,ranked}); });
app.get('/api/reports/summary',requireAuth,(req,res)=>{ const db=readDb(); const patients=db.patients||[]; res.json({ok:true,summary:{total:patients.length,critical:patients.filter(p=>p.status==='critical').length,watch:patients.filter(p=>p.status==='watch').length,stable:patients.filter(p=>p.status==='stable').length,byUnit:patients.reduce((a,p)=>{a[p.unit]=(a[p.unit]||0)+1;return a;},{})}}); });
app.get('/api/audit',requireAuth,(req,res)=>res.json({ok:true,audit:readDb().audit||[]}));
app.listen(PORT,()=>console.log(`HGY CareBoard Pro Suite v3 running at http://localhost:${PORT}`));
